default: &default
  adapter:  postgresql
  host:     postgres
  encoding: unicode
  pool:     10
  template: template0
  port: 5432
  password: postgres
  username: postgres

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production